name: MSBuild

on: [push]

defaults:
  run:
    shell: wsl-bash {0}

jobs:
  build:
    runs-on: windows-latest

    steps:

    - uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-20.04

    - name: find m4
      run: |
          export PYTHON="/mnt/c/Program\ Files\Python\ 3.7\python3.exe"
          export AC_MACRODIR=${{ github.workspace }}/build/autoconf/
          export CC_TYPE=clang
          export CC="/mnt/c/Program\ Files/LLVM/bin/clang.exe"
          export CLANG_CC="/mnt/c/Program\ Files/LLVM/bin/clang.exe"
          export TMPDIR="."
          export OS_ARCH="WINNT"
          export M4=m4
          export AWK=awk
          export MOZTOOLS_PATH='C:\mozilla-build\msys\bin;C:\mozilla-build\bin'
          export AUTOCONF="C:/mozilla-build/msys/local/bin/autoconf-2.13"
          echo envs $M4
          export M4=`which m4`
          echo paths $M4
          export AWK=`which awk`
          env
          echo path $PATH
          export PATH="/mnt/c/Program\ Files/LLVM/bin:$MOZTOOLS_PATH:$PATH"
          echo path $PATH
        
    - name: more ubu stuff
      run: apt install -y m4
        
    - name: find m4
      run: |
          export PYTHON="/mnt/c/Program\ Files\Python\ 3.7\python3.exe"
          export AC_MACRODIR=/mnt/c/Relax/firefox-91.3.0/build/autoconf/
          export CC_TYPE=clang
          export CC="/mnt/c/Program\ Files/LLVM/bin/clang.exe"
          export CLANG_CC="/mnt/c/Program\ Files/LLVM/bin/clang.exe"
          export TMPDIR="."
          export OS_ARCH="WINNT"
          export M4=m4
          export AWK=awk
          export MOZTOOLS_PATH='C:\mozilla-build\msys\bin;C:\mozilla-build\bin'
          export AUTOCONF="C:/mozilla-build/msys/local/bin/autoconf-2.13"
          echo envs $M4
          export M4=`which m4`
          echo paths $M4
          export AWK=`which awk`
          env
          echo path $PATH
          export PATH="/mnt/c/Program\ Files/LLVM/bin:$MOZTOOLS_PATH:$PATH"
          echo path $PATH

    - name: Install deps on windows
      shell: powershell
      run: |
        Start-BitsTransfer -Source https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe -Destination ./MozillaBuildSetup.exe
        .\MozillaBuildSetup.exe /S | Out-Null

    - uses: actions/checkout@v2
          
    - name: moz-compile automake
      continue-on-error: true
      run: |
          mkdir moz-js
          export PYTHON="/mnt/c/Program\ Files\Python\ 3.7\python3.exe"
          export AC_MACRODIR=`pwd`/build/autoconf/          
          export CC_TYPE=clang
          export CC="/mnt/c/LLVM/bin/clang.exe"
          export CLANG_CC="/mnt/c/Program\ Files/LLVM/bin/clang.exe"
          export TMPDIR="."
          export OS_ARCH="WINNT"
          export M4=m4
          export AWK=awk
          export MOZTOOLS_PATH='C:\mozilla-build\msys\bin;C:\mozilla-build\bin'
          export AUTOCONF="C:/mozilla-build/msys/local/bin/autoconf-2.13"
          export PATH="/mnt/c/LLVM/bin:$PATH"
          env
          echo got `which m4`
          echo got `which awk`
          cd js/src
          sh ../../build/autoconf/autoconf.sh --localdir=$PWD configure.in > configure
          
    - name: moz-compile setup
      continue-on-error: true
      run: |
          cd js/src
          chmod +x configure
          mkdir _build
          ln -s /mnt/c/Program\ Files/LLVM /mnt/c/LLVM

      
    - name: moz-compile configure
      continue-on-error: true
      run: |
          mkdir moz-js
          export PYTHON="/mnt/c/Program\ Files\Python\ 3.7\python3.exe"
          export AC_MACRODIR=`pwd`/build/autoconf/          
          export CC_TYPE=clang
          export CC="/mnt/c/LLVM/bin/clang.exe"
          export CLANG_CC="/mnt/c/Program\ Files/LLVM/bin/clang.exe"
          export TMPDIR="."
          export OS_ARCH="WINNT"
          export M4=m4
          export AWK=awk
          export MOZTOOLS_PATH='C:\mozilla-build\msys\bin;C:\mozilla-build\bin'
          export AUTOCONF="C:/mozilla-build/msys/local/bin/autoconf-2.13"
          export PATH="/mnt/c/LLVM/bin:$PATH"
          env
          echo got `which m4`
          echo got `which awk`
          cd js/src/_build
          sh ../configure --disable-ctypes --disable-jit --disable-jemalloc --enable-optimize --enable-hardening --with-intl-api --build-backends=RecursiveMake --with-system-icu --disable-debug --enable-gczeal --prefix=/mnt/c/Relax/vcpkg/installed/x64-windows



    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
