name: MSBuild

on: [push]

defaults:
  run:
    shell: bash

env:
  M4: m4
  AWK: awk
  MOZTOOLS_PATH: 'C:\mozilla-build\msys\bin;C:\mozilla-build\bin'
  AUTOCONF: "C:/mozilla-build/msys/local/bin/autoconf-2.13"

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Install deps on windows
      shell: powershell
      run: |
        Start-BitsTransfer -Source https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe -Destination ./MozillaBuildSetup.exe
        .\MozillaBuildSetup.exe /S | Out-Null

    - uses: actions/checkout@v2
          
    - name: moz-compile ubu setup
      run: |
          mkdir moz-js
          export PYTHON="/mnt/c/Program\ Files\Python\ 3.7\python3.exe"
          export AC_MACRODIR=/mnt/c/Relax/firefox-91.3.0/build/autoconf/
          export CC_TYPE=clang
          export CC="/mnt/c/Program\ Files/LLVM/bin/clang.exe"
          export CLANG_CC="/mnt/c/Program\ Files/LLVM/bin/clang.exe"
          export PATH="/mnt/c/Program\ Files/LLVM/bin:$MOZTOOLS_PATH:$PATH"
          export TMPDIR="."
          export OS_ARCH="WINNT"          
          cd js/src
          sh ../../build/autoconf/autoconf.sh --localdir=$PWD configure.in > configure
          chmod +x configure
          mkdir _build    


    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
